### ISSUE TITLE
Walk backwards option

### ISSUE THREAD

**Issue by VincentVancalbergh** [jconnop/teron#3]
Reverses up and down/left and right.

OOOOR

Flips the whole thing upside down !

**Comment by jconnop** [comment]
Haha I see where you're coming from here - you're probably going to be kiting backwards in the real thing.

The main point of the practice game, though, is to get the ability rotation and positioning down, rather than practicing the movement keys. For most people kiting a mob should be pretty natural I think, and backwards movement in a 2D game where the player has no directionality would be a tad confusing.

Granted, flipping the whole thing upside down would keep the natural 2D controls while also being in line with the buttons you'd use in the real game - but I'd rather not make such a large change at this point.
